services:

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: applied-backend-concepts-docker-database

    ports:
      - "3307:3306"

    volumes:
      - applied-backend-concepts-db-data:/var/lib/mysql

    networks:
      - applied-backend-concepts-docker-network



  app:
    build:
      context: .
      target: runner

    container_name: nextjs-app

    restart: always

    environment:
      PORT: 3000
      DATABASE_URL: mysql://root:admin@db:3306/applied-backend-concepts-docker-database
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: admin
      DATABASE_NAME: applied-backend-concepts-docker-database
      NODE_ENV: production

    ports:
      - "3000:3000"

    depends_on:
      - db

    networks:
      - applied-backend-concepts-docker-network



networks:
  applied-backend-concepts-docker-network:

volumes:
  applied-backend-concepts-db-data: